export type Language = "id" | "en";
export type ThemeMode = "light" | "dark";
export type MainView = "radar" | "latest";

export const copy = {
  id: {
    update: "Terakhir diperbarui",
    refresh: "Perbarui",
    refreshing: "Memuat...",
    search: "Cari topik atau berita...",
    topics: "topik",
    all: "Semua",
    newsRadar: "Berita",
    cultureRadar: "Sosial & Kreator",
    allRadar: "Semua",
    newsRadarHint:
      "Berita, politik, ekonomi, teknologi, olahraga, dan isu global yang sedang naik hari ini.",
    cultureRadarHint:
      "Video, komunitas, dan percakapan sosial yang sedang ramai.",
    allRadarHint: "Gabungan berita dan sosial dalam satu radar.",
    heroTitle: "Temukan tren yang sedang naik sebelum terlambat",
    heroBody:
      "Darinol menyaring berita, video, komunitas, dan percakapan sosial agar kamu bisa menemukan peluang konten lebih cepat.",
    exploreCulture: "Jelajahi tren sosial & kreator",
    readLatest: "Baca berita terbaru",
    categoryPreferences: "Kategori yang kamu minati",
    categoryPreferencesHint: "Pilih satu atau beberapa kategori untuk mempersonalisasi radar.",
    resetCategories: "Reset ke semua kategori",
    radarTab: "Radar Tren",
    latestTab: "Berita Terbaru",
    trendScore: "Skor Tren",
    cultureScore: "Culture Score",
    opportunityScore: "Opportunity Score",
    cultureSample: "Data sampel",
    whyTrending: "Kenapa naik?",
    relatedNews: "Berita Terkait",
    relatedNewsHint: "Klik kartu untuk membuka sumber aslinya.",
    articles: "berita",
    noSource: "Belum ada berita sumber untuk topik ini.",
    nextTopic: "Topik Berikutnya",
    sourceCount: "sumber",
    latestTitle: "Berita Terbaru",
    latestHint: "Diambil langsung dari feed media dan sinyal publik, paling baru di atas.",
    latestEmpty: "Belum ada berita yang cocok dengan pencarianmu.",
    noTopicTitle: "Topik tidak ditemukan",
    noTopicBody: "Coba kata kunci atau kategori lain.",
    light: "Terang",
    dark: "Gelap",
    expand: "Lihat",
    skipToContent: "Lompat ke konten utama",
    viewSwitcher: "Pilih tampilan",
    radarSwitcher: "Pilih radar",
    languageSwitcher: "Pilih bahasa",
    loadingTopics: "Memuat topik",
    loadingArticles: "Memuat berita",
    loadFailed: "Gagal mengambil data tren. Coba perbarui lagi.",
  },
  en: {
    update: "Last updated",
    refresh: "Refresh",
    refreshing: "Loading...",
    search: "Search topic or news...",
    topics: "topics",
    all: "All",
    newsRadar: "News",
    cultureRadar: "Social & Creators",
    allRadar: "All",
    newsRadarHint:
      "News, politics, economy, technology, sports, and global issues trending today.",
    cultureRadarHint:
      "Videos, communities, and social conversations gaining attention.",
    allRadarHint: "News and social signals combined into one radar.",
    heroTitle: "Find rising trends before everyone else",
    heroBody:
      "Darinol filters news, video, communities, and social conversations so you can spot content opportunities faster.",
    exploreCulture: "Explore social & creator trends",
    readLatest: "Read the latest news",
    categoryPreferences: "Categories you follow",
    categoryPreferencesHint: "Choose one or more categories to personalize your radar.",
    resetCategories: "Reset to all categories",
    radarTab: "Trend Radar",
    latestTab: "Latest News",
    trendScore: "Trend Score",
    cultureScore: "Culture Score",
    opportunityScore: "Opportunity Score",
    cultureSample: "Sample data",
    whyTrending: "Why is it rising?",
    relatedNews: "Related News",
    relatedNewsHint: "Click a card to open the original source.",
    articles: "articles",
    noSource: "No source articles for this topic yet.",
    nextTopic: "Next Topic",
    sourceCount: "sources",
    latestTitle: "Latest News",
    latestHint: "Pulled straight from media feeds and public signals, newest first.",
    latestEmpty: "No news matches your search yet.",
    noTopicTitle: "No topic found",
    noTopicBody: "Try another keyword or category.",
    light: "Light",
    dark: "Dark",
    expand: "Show",
    skipToContent: "Skip to main content",
    viewSwitcher: "Choose a view",
    radarSwitcher: "Choose a radar",
    languageSwitcher: "Choose a language",
    loadingTopics: "Loading topics",
    loadingArticles: "Loading news",
    loadFailed: "Failed to fetch trend data. Try refreshing again.",
  },
} as const;

export type Copy = (typeof copy)[Language];

export const newsCategoryFilters = [
  "Semua",
  "Peristiwa",
  "Business",
  "Technology",
  "Crypto",
  "Politics",
  "Sports",
  "Entertainment",
  "Global",
  "Social",
  "General",
];

export const cultureCategoryFilters = [
  "Semua",
  "music",
  "meme",
  "lifestyle",
  "fashion",
  "food",
  "beauty",
  "gaming",
  "film",
  "internet_slang",
  "entertainment",
  "creator_trend",
  "tech_community",
];
