export type Language = "id" | "en";
export type ThemeMode = "light" | "dark";
export type MainView = "radar" | "latest";

export const copy = {
  id: {
    update: "Terakhir diperbarui",
    refresh: "Perbarui",
    refreshing: "Memuat...",
    search: "Cari topik atau berita...",
    topics: "topik",
    all: "Semua",
    newsRadar: "Berita",
    cultureRadar: "Culture",
    allRadar: "Semua Radar",
    newsRadarHint:
      "Berita, politik, ekonomi, teknologi, olahraga, dan isu global yang sedang naik hari ini.",
    cultureRadarHint:
      "Internet culture, meme, musik, lifestyle, dan percakapan komunitas yang sedang naik.",
    allRadarHint: "Gabungan radar berita dan culture dalam satu daftar.",
    radarTab: "Radar Tren",
    latestTab: "Berita Terbaru",
    trendScore: "Skor Tren",
    cultureScore: "Culture Score",
    opportunityScore: "Opportunity Score",
    cultureSample: "Data sampel",
    whyTrending: "Kenapa naik?",
    relatedNews: "Berita Terkait",
    relatedNewsHint: "Klik kartu untuk membuka sumber aslinya.",
    articles: "berita",
    noSource: "Belum ada berita sumber untuk topik ini.",
    nextTopic: "Topik Berikutnya",
    sourceCount: "sumber",
    latestTitle: "Berita Terbaru",
    latestHint: "Diambil langsung dari feed media dan sinyal publik, paling baru di atas.",
    latestEmpty: "Belum ada berita yang cocok dengan pencarianmu.",
    noTopicTitle: "Topik tidak ditemukan",
    noTopicBody: "Coba kata kunci atau kategori lain.",
    light: "Terang",
    dark: "Gelap",
    expand: "Lihat",
    skipToContent: "Lompat ke konten utama",
    viewSwitcher: "Pilih tampilan",
    radarSwitcher: "Pilih radar",
    languageSwitcher: "Pilih bahasa",
    loadingTopics: "Memuat topik",
    loadingArticles: "Memuat berita",
    loadFailed: "Gagal mengambil data tren. Coba perbarui lagi.",
  },
  en: {
    update: "Last updated",
    refresh: "Refresh",
    refreshing: "Loading...",
    search: "Search topic or news...",
    topics: "topics",
    all: "All",
    newsRadar: "News",
    cultureRadar: "Culture",
    allRadar: "All Radars",
    newsRadarHint:
      "News, politics, economy, technology, sports, and global issues trending today.",
    cultureRadarHint:
      "Internet culture, memes, music, lifestyle, and community conversations on the rise.",
    allRadarHint: "News radar and culture radar combined into one list.",
    radarTab: "Trend Radar",
    latestTab: "Latest News",
    trendScore: "Trend Score",
    cultureScore: "Culture Score",
    opportunityScore: "Opportunity Score",
    cultureSample: "Sample data",
    whyTrending: "Why is it rising?",
    relatedNews: "Related News",
    relatedNewsHint: "Click a card to open the original source.",
    articles: "articles",
    noSource: "No source articles for this topic yet.",
    nextTopic: "Next Topic",
    sourceCount: "sources",
    latestTitle: "Latest News",
    latestHint: "Pulled straight from media feeds and public signals, newest first.",
    latestEmpty: "No news matches your search yet.",
    noTopicTitle: "No topic found",
    noTopicBody: "Try another keyword or category.",
    light: "Light",
    dark: "Dark",
    expand: "Show",
    skipToContent: "Skip to main content",
    viewSwitcher: "Choose a view",
    radarSwitcher: "Choose a radar",
    languageSwitcher: "Choose a language",
    loadingTopics: "Loading topics",
    loadingArticles: "Loading news",
    loadFailed: "Failed to fetch trend data. Try refreshing again.",
  },
} as const;

export type Copy = (typeof copy)[Language];

export const newsCategoryFilters = [
  "Semua",
  "Peristiwa",
  "Business",
  "Technology",
  "Crypto",
  "Politics",
  "Sports",
  "Entertainment",
  "Global",
  "Social",
  "General",
];

export const cultureCategoryFilters = [
  "Semua",
  "music",
  "meme",
  "lifestyle",
  "fashion",
  "food",
  "beauty",
  "gaming",
  "film",
  "internet_slang",
  "entertainment",
  "creator_trend",
];
