export type Language = "id" | "en";
export type ThemeMode = "light" | "dark";
export type MainView = "radar" | "latest";

export const copy = {
  id: {
    update: "Diperbarui",
    refresh: "Perbarui radar",
    refreshing: "Memperbarui...",
    search: "Cari topik, sumber, atau berita",
    topics: "sinyal",
    all: "Semua",
    newsRadar: "Berita",
    cultureRadar: "Sosial & Kreator",
    allRadar: "Semua",
    newsRadarHint:
      "Berita, politik, ekonomi, teknologi, olahraga, dan isu global yang sedang naik hari ini.",
    cultureRadarHint:
      "Video, komunitas, dan percakapan sosial yang sedang ramai.",
    allRadarHint: "Gabungan berita dan sosial dalam satu radar.",
    heroTitle: "Sinyal yang sedang bergerak.",
    heroBody:
      "Radar tren untuk melihat apa yang sedang naik, seberapa cepat pergerakannya, dan dari mana sinyalnya datang.",
    exploreCulture: "Lihat tren sosial & kreator",
    readLatest: "Buka berita terbaru",
    categoryPreferences: "Sesuaikan radar",
    categoryPreferencesHint: "Pilih satu atau beberapa kategori untuk memprioritaskan sinyal yang tampil.",
    resetCategories: "Reset ke semua kategori",
    moreCategories: "Semua Kategori",
    categoryDropdownLabel: "Pilih kategori lain",
    radarTab: "Radar Tren",
    latestTab: "Berita Terbaru",
    trendScore: "Skor Tren",
    cultureScore: "Culture Score",
    opportunityScore: "Opportunity Score",
    cultureSample: "Data sampel",
    whyTrending: "Mengapa topik ini bergerak",
    relatedNews: "Berita dan sumber terkait",
    relatedNewsHint: "Klik kartu untuk membuka sumber aslinya.",
    articles: "berita",
    noSource: "Belum ada berita sumber untuk topik ini.",
    nextTopic: "Lihat sinyal berikutnya",
    sourceCount: "sumber",
    latestTitle: "Berita Terbaru",
    latestHint: "Diambil langsung dari feed media dan sinyal publik, paling baru di atas.",
    latestEmpty: "Belum ada berita yang cocok dengan pencarianmu.",
    noTopicTitle: "Tidak ada sinyal yang cocok",
    noTopicBody: "Coba kategori lain atau reset filter.",
    light: "Terang",
    dark: "Gelap",
    expand: "Lihat",
    skipToContent: "Lompat ke konten utama",
    viewSwitcher: "Pilih tampilan",
    radarSwitcher: "Pilih radar",
    languageSwitcher: "Pilih bahasa",
    loadingTopics: "Mengambil sinyal tren terbaru",
    loadingArticles: "Mengambil berita terkait",
    loadFailed: "Gagal mengambil data tren. Coba perbarui lagi.",
  },
  en: {
    update: "Updated",
    refresh: "Refresh radar",
    refreshing: "Refreshing...",
    search: "Search topics, sources, or news",
    topics: "signals",
    all: "All",
    newsRadar: "News",
    cultureRadar: "Social & Creators",
    allRadar: "All",
    newsRadarHint:
      "News, politics, economy, technology, sports, and global issues trending today.",
    cultureRadarHint:
      "Videos, communities, and social conversations gaining attention.",
    allRadarHint: "News and social signals combined into one radar.",
    heroTitle: "Signals on the move.",
    heroBody:
      "A trend radar for what is rising, how fast it is moving, and where the signal is coming from.",
    exploreCulture: "See social & creator trends",
    readLatest: "Open the latest news",
    categoryPreferences: "Adjust your radar",
    categoryPreferencesHint: "Choose one or more categories to prioritize which signals show up.",
    resetCategories: "Reset to all categories",
    moreCategories: "All Categories",
    categoryDropdownLabel: "Choose another category",
    radarTab: "Trend Radar",
    latestTab: "Latest News",
    trendScore: "Trend Score",
    cultureScore: "Culture Score",
    opportunityScore: "Opportunity Score",
    cultureSample: "Sample data",
    whyTrending: "Why this topic is moving",
    relatedNews: "Related coverage and sources",
    relatedNewsHint: "Click a card to open the original source.",
    articles: "articles",
    noSource: "No source articles for this topic yet.",
    nextTopic: "See the next signal",
    sourceCount: "sources",
    latestTitle: "Latest News",
    latestHint: "Pulled straight from media feeds and public signals, newest first.",
    latestEmpty: "No news matches your search yet.",
    noTopicTitle: "No matching signal",
    noTopicBody: "Try another category or reset your filters.",
    light: "Light",
    dark: "Dark",
    expand: "Show",
    skipToContent: "Skip to main content",
    viewSwitcher: "Choose a view",
    radarSwitcher: "Choose a radar",
    languageSwitcher: "Choose a language",
    loadingTopics: "Fetching the latest trend signals",
    loadingArticles: "Fetching related coverage",
    loadFailed: "Failed to fetch trend data. Try refreshing again.",
  },
} as const;

export type Copy = (typeof copy)[Language];

export const newsCategoryFilters = [
  "Semua",
  "Peristiwa",
  "Business",
  "Technology",
  "Crypto",
  "Politics",
  "Sports",
  "Entertainment",
  "Global",
  "Social",
  "General",
];

export const cultureCategoryFilters = [
  "Semua",
  "music",
  "meme",
  "lifestyle",
  "fashion",
  "food",
  "beauty",
  "gaming",
  "film",
  "internet_slang",
  "entertainment",
  "creator_trend",
  "tech_community",
];
